#!/usr/bin/env bash
# Sync mode script for ADR Buddy GitHub Action
# Creates branch, commits ADR changes, and creates PR

set -euo pipefail

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

# Check if changes exist
if [ -z "$(git status --porcelain)" ]; then
  echo "No ADR changes to commit"
  set_output "changes-detected" "false"
  exit 0
fi

set_output "changes-detected" "true"

# Configure git
git config user.name "adr-buddy[bot]"
git config user.email "adr-buddy[bot]@users.noreply.github.com"

# Create timestamped branch
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="adr-buddy/sync-${TIMESTAMP}"
git checkout -b "$BRANCH_NAME"

# Commit ADR changes
git add -A
COMMIT_SHA=$(git rev-parse --short HEAD)
COMMIT_MSG="chore(docs): sync ADRs from ${COMMIT_SHA}

Automated ADR synchronization based on code annotations.

Co-Authored-By: ADR Buddy <adr-buddy[bot]@users.noreply.github.com>"

git commit -m "$COMMIT_MSG"

# Push branch
git push origin "$BRANCH_NAME"

# Skip PR creation if disabled
if [ "$CREATE_PR" != "true" ]; then
  echo "PR creation disabled, branch pushed: $BRANCH_NAME"
  exit 0
fi

# Check for existing sync PR
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -n "$EXISTING_PR" ]; then
  echo "PR already exists: #$EXISTING_PR"
  set_output "pr-number" "$EXISTING_PR"
  PR_URL=$(gh pr view "$EXISTING_PR" --json url --jq '.url')
  set_output "pr-url" "$PR_URL"
  exit 0
fi

# Get trigger commit info
TRIGGER_SHA=$(git log origin/$(git rev-parse --abbrev-ref HEAD@{upstream} 2>/dev/null || echo "main") -1 --format=%h 2>/dev/null || echo "latest")
TRIGGER_MSG=$(git log origin/$(git rev-parse --abbrev-ref HEAD@{upstream} 2>/dev/null || echo "main") -1 --format=%s 2>/dev/null || echo "recent changes")

# Build PR body
PR_BODY="## ADR Sync

Updates Architecture Decision Records based on code annotations.

**Triggered by:** ${TRIGGER_SHA} - ${TRIGGER_MSG}

### Changes
"

# List changed files
CREATED_FILES=$(git diff --name-status origin/main...HEAD | grep "^A" | cut -f2 || true)
MODIFIED_FILES=$(git diff --name-status origin/main...HEAD | grep "^M" | cut -f2 || true)

if [ -n "$CREATED_FILES" ]; then
  PR_BODY+="
**Created:**
"
  while IFS= read -r file; do
    PR_BODY+="- $file
"
  done <<< "$CREATED_FILES"
fi

if [ -n "$MODIFIED_FILES" ]; then
  PR_BODY+="
**Modified:**
"
  while IFS= read -r file; do
    PR_BODY+="- $file
"
  done <<< "$MODIFIED_FILES"
fi

PR_BODY+="

---
🤖 Generated by [ADR Buddy](https://github.com/weaby/adr-buddy)"

# Create PR
PR_TITLE="[ADR Buddy] Sync ADRs from ${COMMIT_SHA}"

gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --label "documentation,automated" \
  --base main

# Get PR number and URL
PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')
PR_URL=$(gh pr view "$PR_NUMBER" --json url --jq '.url')

set_output "pr-number" "$PR_NUMBER"
set_output "pr-url" "$PR_URL"

# Add reviewers if specified
if [ -n "$REVIEWERS" ]; then
  IFS=',' read -ra REVIEWER_ARRAY <<< "$REVIEWERS"
  for reviewer in "${REVIEWER_ARRAY[@]}"; do
    reviewer=$(echo "$reviewer" | xargs) # trim whitespace
    gh pr edit "$PR_NUMBER" --add-reviewer "$reviewer" || echo "Failed to add reviewer: $reviewer"
  done
fi

echo "Created PR #${PR_NUMBER}: ${PR_URL}"
